### PR TITLE
fix(sandbox): landlock 0.4.5 API compatibility

### LINKED ISSUE #96: Build failure: landlock 0.4.5 API incompatibility (BitFlags<AccessFs> migration)
## Summary

`crab-sandbox` fails to compile with the latest `landlock = "0.4"` (resolves to 0.4.5). The `landlock` crate made a breaking change within the 0.4.x series: `AccessFs` methods now return `BitFlags<AccessFs>` instead of `AccessFs`, and `RulesetHandle` has been removed.

## Errors

```
error[E0432]: unresolved import `landlock::RulesetHandle`
error[E0599]: no method named `add_rules` found for struct `RulesetCreated`  (needs `RulesetCreatedAttr` trait in scope)
error[E0308]: mismatched types — expected `AccessFs`, found `BitFlags<AccessFs, u64>`
error[E0599]: no associated function `from_all` found for `AccessFs` (needs `Access` trait in scope)
```

## Root Cause

`Cargo.toml` declares `landlock = "0.4"`, which now resolves to 0.4.5. The landlock crate changed:

1. `from_all()` / `from_read()` / `from_write()` on `AccessFs` now return `BitFlags<AccessFs>` instead of `AccessFs`
2. `RulesetHandle` type removed entirely
3. `add_rules()` method requires `RulesetCreatedAttr` trait to be in scope
4. `from_all()` requires `Access` trait to be in scope

## Fix

See the associated PR. Changes are confined to `crates/sandbox/src/backend/landlock.rs`:

- Import `Access`, `BitFlags`, `RulesetCreatedAttr` from landlock
- Remove unused `RulesetHandle` import
- Change `path_access_to_landlock` return type to `BitFlags<AccessFs>`
- Remove incorrect `.into()` calls

## Environment

- OS: Debian 6.1.153-1 (x86_64)
- Rust: 1.96.0
- landlock crate resolved: 0.4.5

### PR DESCRIPTION
**Pull request by Svtter**
## Problem

`crab-sandbox` fails to compile with `landlock = "0.4"` (resolves to 0.4.5). The landlock crate made a breaking change within the 0.4.x semver range.

Closes #96

## Changes

All changes in `crates/sandbox/src/backend/landlock.rs`:

1. **Imports**: Added `Access`, `BitFlags`, `RulesetCreatedAttr`; removed unused `RulesetHandle`
2. **Return type**: `path_access_to_landlock` now returns `BitFlags<AccessFs>` instead of `AccessFs`
3. **Removed `.into()` calls**: `from_read`/`from_write`/`from_all` already return `BitFlags<AccessFs>`

## Verification

```bash
cargo build --release -p crab-cli
# Compiles successfully, produces 34M binary
```

## Error messages before fix

```
error[E0432]: unresolved import `landlock::RulesetHandle`
error[E0599]: no method named `add_rules` found (needs RulesetCreatedAttr trait)
error[E0308]: expected `AccessFs`, found `BitFlags<AccessFs, u64>`
error[E0599]: no associated function `from_all` (needs Access trait)
```

### CODE REVIEW

**Comment by lingcoder** [comment]
Thanks for turning the report into a fix, @Svtter — much appreciated.

`main` already carries an equivalent fix that landed from a different base: `72c8530` (the `BitFlags<AccessFs>` return type + `Access` trait import) plus `c381d7d` (the clippy lints that appear once the crate compiles again). Because it was fixed against a different base, this PR now conflicts and is effectively superseded, so I am going to close it.

Closing as already-fixed-on-main — thanks again for catching this and for the precise root-cause analysis in #96.
